/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./**/*.php",
    "./src/**/*.css",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131313",
        "inverse-surface": "#e5e2e1",
        tertiary: "#ccc6be",
        "on-tertiary": "#33302b",
        outline: "#9f8e7e",
        primary: "#ffb963",
        "on-tertiary-container": "#2c2924",
        "inverse-primary": "#865300",
        "surface-container": "#201f1f",
        "on-background": "#e5e2e1",
        "outline-variant": "#514437",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#c4832d",
        "primary-fixed-dim": "#ffb963",
        "on-tertiary-fixed": "#1e1b17",
        "primary-fixed": "#ffddb9",
        "on-error-container": "#ffdad6",
        "surface-tint": "#ffb963",
        "on-surface": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        background: "#131313",
        "tertiary-fixed": "#e8e1da",
        "on-secondary": "#303030",
        secondary: "#c7c6c6",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary-container": "#b6b5b5",
        "surface-container-highest": "#353534",
        "surface-container-low": "#1c1b1b",
        error: "#ffb4ab",
        "on-primary-container": "#3e2400",
        "on-primary-fixed": "#2b1700",
        "surface-bright": "#393939",
        "tertiary-container": "#959089",
        surface: "#131313",
        "secondary-fixed": "#e4e2e2",
        "inverse-on-surface": "#313030",
        "tertiary-fixed-dim": "#ccc6be",
        "on-primary": "#472a00",
        "on-surface-variant": "#d6c3b1",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#464747",
        "on-tertiary-fixed-variant": "#4a4641",
        "on-primary-fixed-variant": "#663e00",
        "secondary-container": "#464747",
        "surface-variant": "#353534",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
